Add login page
kPoziomek/blog-app pull request #4
Opened 2022-02-08 12:26 UTC by kPoziomek

2022-02-14 11:14 UTC, ewydra requested changes

2022-02-14 11:14 UTC, ewydra commented on src/pages/CreateArticle.js
> +    console.log(values);
✂️

2022-02-14 11:14 UTC, ewydra commented on src/pages/CreateArticle.js
> +          </CardActions>{' '}
`{' '}` ✂️

2022-02-14 11:14 UTC, ewydra commented on src/pages/Article.js
> +      ) : null}
`{articleData && ...}`

2022-02-14 11:14 UTC, ewydra commented on src/components/Navigation.js
> +        localStorage.setItem('tokenId', userData.id);
Are you using `tokenId` from localStorage somewhere in the app?

2022-02-14 11:14 UTC, ewydra commented on src/components/Navigation.js
> +                {userName ? `Hello ${userName}` : 'Hello Stranger'}
How about `Hello ${userName ?? "Stranger"}`?

2022-02-14 11:17 UTC, kPoziomek commented on package.json
>      "@mui/material": "^5.4.0",
npm

2022-02-14 14:54 UTC, kPoziomek reviewed
done

2022-02-14 20:37 UTC, ewydra requested changes

2022-02-14 20:37 UTC, ewydra commented on src/pages/components/BlogThumbnailContent.js
> +  const { author } = arr;
You can use more meaningful name than `arr`, eg. `article`. Also, you can get author, title and summary using one line:
```
const { title, summary, author } = article
```

2022-02-14 20:37 UTC, ewydra commented on src/App.js
> +        <Route path="createarticle" exact element={<CreateArticle />} />
Please use something like `/articles/create` to improve readability

2022-02-14 20:37 UTC, ewydra commented on package.json
>      "@material-ui/lab": "^4.0.0-alpha.60",
Please remove `@material-ui/core` and `@material-ui/lab` packages

2022-02-14 20:37 UTC, ewydra commented on src/pages/CreateArticle.js
>                </IconButton>
This component is getting big and it could be separated to another file, but it can be done on new branch

2022-02-14 20:37 UTC, ewydra commented on src/pages/Article.js
> +};
Try to replace icons here and in other components by [material icons](https://mui.com/components/material-icons/)

2022-02-14 20:37 UTC, ewydra commented on src/pages/CreateArticle.js
> +  const validationSchema = yup.object({});
You can remove this `validationSchema` as it is empty

2022-02-15 11:07 UTC, kPoziomek commented on src/pages/components/BlogThumbnailContent.js
> +  const { author } = arr;
done

2022-02-15 11:08 UTC, kPoziomek commented on src/App.js
> +        <Route path="createarticle" exact element={<CreateArticle />} />
done

2022-02-15 11:08 UTC, kPoziomek commented on package.json
>      "@material-ui/lab": "^4.0.0-alpha.60",
done

2022-02-15 11:35 UTC, kPoziomek commented on src/pages/Article.js
> +};
done

2022-02-15 11:57 UTC, kPoziomek commented on src/pages/CreateArticle.js
>                </IconButton>
removed Menu from component

2022-02-15 11:57 UTC, kPoziomek commented on src/pages/CreateArticle.js
> +  const validationSchema = yup.object({});
done

2022-02-15 12:09 UTC, ewydra requested changes

2022-02-15 12:09 UTC, ewydra commented on src/pages/CreateArticle.js
> +};
Here is one more icon that should be replaced by material ui icon

2022-02-15 12:09 UTC, ewydra commented on src/pages/Login.js
>  };
Here is one more icon that should be replaced by material ui icon

2022-02-15 12:11 UTC, kPoziomek commented on src/App.js
> +        <Route path="createarticle" exact element={<CreateArticle />} />
switched to /create

2022-02-15 12:39 UTC, ewydra approved these changes

2022-02-15 12:52 UTC, merged