styling create article form
kPoziomek/blog-app pull request #5
Opened 2022-02-15 13:03 UTC by kPoziomek

2022-02-16 10:59 UTC, ewydra requested changes

2022-02-16 10:59 UTC, ewydra commented on src/pages/Article.js
> +            <ReactMarkdown children={articleData.title} />
Why are you using react-markdown here?

2022-02-16 10:59 UTC, ewydra commented on src/pages/CreateArticle.css
> +}
are these styles changing anything in the component layout?

2022-02-16 10:59 UTC, ewydra commented on src/pages/CreateArticle.js
> +classNames.bind(styles);
I think you don't need to use `bind` method for classNames as you are not using `css-modules`

2022-02-16 10:59 UTC, ewydra commented on src/pages/CreateArticle.js
> +      navigate('/articles/' + id);
``navigate(`articles/${id}`)``

2022-02-16 10:59 UTC, ewydra commented on src/pages/CreateArticle.js
> +              <p className={errorText}>Fill up content field</p>
Instead using classNames, you can render this element conditionally. Also you should display value of `formik.errors.content` here

2022-02-16 10:59 UTC, ewydra commented on src/pages/CreateArticle.js
> +              <p className={errorText}>Fill up content field</p>
You can create separate component from this code

2022-02-16 10:59 UTC, ewydra commented on src/pages/CreateArticle.css
> +  display: flex;
I'm not sure if you need all these styles to be specified

2022-02-16 10:59 UTC, ewydra commented on src/pages/CreateArticle.css
> +}
are these styles changing anything in the component layout?

2022-02-16 10:59 UTC, ewydra commented on src/pages/CreateArticle.css
> +  margin: 10px 0 !important;
do you need `important!` here?

2022-02-16 10:59 UTC, ewydra commented on src/pages/Article.js
> +            />
It would be better if you use something like `p` with `dangerouslySetInnerHTML` here instead of `ReactQuill`. Remember to sanitize the content that you are displaying using this method.
https://blog.logrocket.com/using-dangerouslysetinnerhtml-in-a-react-application/
https://www.npmjs.com/package/dompurify

2022-02-16 11:14 UTC, kPoziomek commented on src/pages/CreateArticle.css
> +}
yes, and I need them there.

2022-02-16 11:15 UTC, kPoziomek commented on src/pages/CreateArticle.js
> +classNames.bind(styles);
done

2022-02-16 11:16 UTC, kPoziomek commented on src/pages/CreateArticle.js
> +      navigate('/articles/' + id);
done

2022-02-16 11:18 UTC, kPoziomek commented on src/pages/Article.js
> +            />
done

2022-02-16 11:29 UTC, kPoziomek commented on src/pages/CreateArticle.js
> +              <p className={errorText}>Fill up content field</p>
done

2022-02-16 11:33 UTC, kPoziomek commented on src/pages/CreateArticle.css
> +  display: flex;
I just removed a bit of them

2022-02-16 11:36 UTC, kPoziomek commented on src/pages/CreateArticle.css
> +}
yes, i need them because i need overwrite a main styles

2022-02-17 11:15 UTC, kPoziomek commented on src/pages/CreateArticle.js
> +              <p className={errorText}>Fill up content field</p>
done

2022-02-17 11:54 UTC, ewydra requested changes

2022-02-17 11:54 UTC, ewydra commented on src/pages/CreateArticle.js
> +  const [childData, setChildData] = useState('');
I think you don't need this state

2022-02-17 12:05 UTC, kPoziomek commented on src/pages/CreateArticle.js
> +  const [childData, setChildData] = useState('');
done

2022-02-17 12:09 UTC, ewydra requested changes

2022-02-17 12:09 UTC, ewydra commented on src/pages/CreateArticle.css
> +} */
✂️

2022-02-17 12:09 UTC, ewydra commented on src/pages/CreateArticle.js
> +      .min(2, 'Write your title')
Why have this changed?

2022-02-17 13:30 UTC, ewydra approved these changes

2022-02-17 13:30 UTC, merged