added arr with cards
kPoziomek/blog-app pull request #6
Opened 2022-02-17 14:59 UTC by kPoziomek

2022-02-22 14:52 UTC, ewydra requested changes

2022-02-22 14:52 UTC, ewydra commented on src/pages/MyArticles.js
> +                </CardContent>
Is it possible to reuse article card content from the homepage or is it very different from this one?

2022-02-22 14:52 UTC, ewydra commented on src/pages/MyEditedArticle.js
> +
I think passing article as a state when navigating to this component is not the best practice. How about changing pathname of this page to something that will contain article id, eg. `/articles/edit/:articleId` so you can get this id using 
```
const { articleId } = useParams()
```
Then you can fetch this article from the backend (that will not be necessary when we'll introduce state management but I think for now this is best practice)

2022-02-22 14:52 UTC, ewydra commented on src/pages/components/ArticleForm.js
> +  };
I am not sure what is the purpose of setting this `type.id` - it is a bit confusing. You can pass the type by using simple string ('create' and 'edit'), pass boolean prop (eg. `isEditMode`) or create constant values in new file:
```
const formTypes = {
  CREATE: 'CREATE',
  EDIT: 'EDIT'
}
```
and pass it as a type: `<ArticleForm type={formTypes.CREATE} ... />` - this will protect us from typos

2022-02-23 09:14 UTC, kPoziomek commented on src/pages/MyArticles.js
> +        setMyArticles(filteredArticle);
done

2022-02-23 09:14 UTC, kPoziomek commented on src/components/Navigation.js
> +                    onClick={() => null}
done

2022-02-23 09:14 UTC, kPoziomek commented on src/App.js
> +        <Route path="editedarticle" exact element={<MyEditedArticle />} />
done

2022-02-23 09:19 UTC, kPoziomek commented on src/pages/MyArticles.js
> +          myArticles.map((arr) => {
done

2022-02-23 09:21 UTC, kPoziomek commented on src/pages/components/ArticleForm.js
> +  const { type, formData } = props;
done

2022-02-23 09:47 UTC, kPoziomek commented on src/pages/components/ArticleForm.js
> +  };
done

2022-02-23 11:05 UTC, kPoziomek commented on src/components/Navigation.js
> +                    </Button>
rebuilt to menu

2022-02-23 13:04 UTC, kPoziomek commented on src/pages/MyEditedArticle.js
> +
done

2022-02-24 08:12 UTC, kPoziomek commented on src/components/Navigation.js
> +                : null}
done

2022-02-24 08:13 UTC, kPoziomek commented on src/pages/Article.js
> +  console.log(articleData);
done

2022-02-24 08:14 UTC, kPoziomek commented on src/pages/Home.js
> +  }
done

2022-02-24 08:15 UTC, kPoziomek commented on src/pages/MyEditedArticle.js
> +  console.log(singleArticleData);
done

2022-02-24 08:15 UTC, kPoziomek commented on src/pages/MyEditedArticle.js
> +        {' '}
done

2022-02-24 08:17 UTC, kPoziomek commented on src/pages/components/ArticleForm.js
> +      EditSingleArticle(dataFromEdit.id, values).then((data) => {
done

2022-02-24 08:17 UTC, kPoziomek commented on src/pages/components/ArticleForm.js
> +    if (formType === 'CREATE') {
done

2022-02-24 08:47 UTC, kPoziomek commented on src/pages/components/ArticleForm.js
> +  const [dataFromEdit, setDataFromEdit] = useState(formData);
done

2022-02-24 11:29 UTC, kPoziomek commented on src/components/Navigation.js
> +            </Menu>
done

2022-02-24 13:06 UTC, kPoziomek commented on src/pages/MyArticles.js
> +                </CardContent>
done

2022-02-25 13:56 UTC, ewydra requested changes

2022-02-25 13:56 UTC, ewydra commented on src/helpers/FormHelper.js
> +};
I think you don't need this anymore :)

2022-02-25 13:56 UTC, ewydra commented on src/pages/components/BlogThumbnailContent.js
> +      </>
i think it would be better if you send boolean prop that determines whether the image should be displayed (eg. `withImage`)

2022-02-25 14:10 UTC, ewydra approved these changes

2022-02-25 14:10 UTC, merged